# Generated by Django 4.2 on 2023-04-21 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_news_new'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='Post',
        ),
    ]
