# Generated by Django 4.2 on 2023-04-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_is_published_post_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kategori',
            field=models.ManyToManyField(to='api.category'),
        ),
    ]
