# Generated by Django 4.2 on 2023-04-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_post_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
