# Generated by Django 4.2 on 2023-04-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nim',
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
    ]
