# Generated by Django 4.2 on 2023-04-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_nim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nim',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
