# Generated by Django 4.2 on 2023-05-06 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publisher',
        ),
    ]
