# Generated by Django 4.2 on 2023-05-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_post_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hero_img',
            field=models.ImageField(default='', upload_to='post/image'),
            preserve_default=False,
        ),
    ]
