# Generated by Django 4.2 on 2023-05-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_post_hero_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hero_img',
            field=models.ImageField(blank=True, upload_to='post/image'),
        ),
    ]
